App.Web/Models/ClientPaymentViewModel.cs
using System;
using System.Activities.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using App.Entity.Models;
using Foolproof;

namespace App.Web.Models
{
    public class ClientPaymentViewModel
    {
        public ClientPaymentViewModel()
        {
            PaymentDate = DateTime.Now;
        }

        [Required]
        [Display(Name = "Branch")]
        public int BranchId { get; set; }

        [Required]
        [Display(Name = "Customer")]
        public int CustomerId { get; set; }

        [Required]
        [Display(Name = "Service Amt")]
        public double ServiceAmount { get; set; }

        [Required]
        [Display(Name = "Paid Amt")]
        public double PaidAmount { get; set; }

        [Required]
        [Display(Name = "Due Amt")]
        public double DueAmount { get; set; }

        [Display(Name = "Payment Date")]
        [Required(ErrorMessage = "Select a date for payment.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime PaymentDate { get; set; }

        [Display(Name = "Payment Amount")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Payment amount must be greater than 0")]
        [LessThanOrEqualTo("DueAmount", ErrorMessage = "Payment amount cannot be greater than Due amount")]
        public double PaymentAmount { get; set; }

        [Display(Name = "Payment Method")]
        public int? MethodId { get; set; }

        [Required]
        public Channel Channel { get; set; }

        [Required]
        public Status Status { get; set; }
    }
}

App.Web/Controllers/BillingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using App.Entity.Models;
using App.Web.Context;
using App.Web.Helper;
using App.Web.Models;

namespace App.Web.Controllers
{
    [CrmAuthorize(Roles = "Admin,Agent")]
    [CrmPermission]
    public class BillingController : Controller
    {
        #region Private Zone

        private readonly CrmDbContext _db;

        #endregion

        public BillingController()
        {
            _db = new CrmDbContext();
        }

        [CrmAuthorize(Roles = "Admin,Agent")]
        [HttpGet]
        public ActionResult ClientPayment()
        {
            if (User.IsInRole("Admin"))
            {
                ViewBag.BranchList = new SelectList(_db.BranchInfos.ToList(), "Id", "BranchName");            
                ViewBag.ClientList = new SelectList(new List<ClientInfo>());
            }
            else if (User.IsInRole("Agent"))
            {
                var agentId = _db.AgentInfos.First(x => x.UserName == User.Identity.Name).Id;
                ViewBag.ClientList = new SelectList(_db.ClientInfos.Where(x => x.AgentId == agentId).ToList(), "Id", "FirstName");
            }
            return View();
        }

        [CrmAuthorize(Roles = "Admin,Agent")]
        [HttpPost]
        public ActionResult ClientPayment(ClientPaymentViewModel payment)
        {
            try
            {
                ModelState.Clear();
                if (User.IsInRole("Agent"))
                {
                    var branchId = _db.ClientInfos.Where(x => x.Id == payment.CustomerId).Select(x=>x.BranchId).FirstOrDefault() 
                        ?? _db.BranchInfos.Where(x => x.BranchName == "Main").Select(x => x.Id).FirstOrDefault();
                    payment.BranchId = branchId;
                }

                payment.Channel = Channel.IsCustomer;
                payment.Status = Status.Active;

                TryValidateModel(payment);
                if (!ModelState.IsValid) return Json(new { Flag = false, Msg = "Invalid payment info." });
                if (payment.PaymentAmount > payment.DueAmount)
                    return Json(new { Flag = false, Msg = "Payment amount cannot be greater than Due amount."});
                if (payment.PaymentAmount > payment.ServiceAmount)
                    return Json(new { Flag = false, Msg = "Payment amount cannot be greater than Service amount." });
                
                using (var dbTransaction = _db.Database.BeginTransaction())
                {
                    try
                    {
                        var clientPayment = new CustomerPayment
                        {
                            BranchId = payment.BranchId,
                            CustomerId = payment.CustomerId,
                            PaymentDate = payment.PaymentDate,
                            PaymentAmount = payment.PaymentAmount,
                            EntryDate = DateTime.Now,
                            Status = payment.Status,
                            Channel = payment.Channel
                        };
                        if (User.IsInRole("Admin"))
                        {
                            clientPayment.UserType = UserType.IsAdmin;
                            clientPayment.EntryBy = _db.Users.First(x => x.UserName == User.Identity.Name).Id;
                        }
                        if (User.IsInRole("Agent"))
                        {
                            clientPayment.UserType = UserType.IsAgent;
                            clientPayment.EntryBy = _db.AgentInfos.First(x => x.UserName == User.Identity.Name).Id;
                        }
                        _db.CustomerPayments.Add(clientPayment);
                        _db.SaveChanges();
                        dbTransaction.Commit();
                        return Json(new { Flag = true, Msg = "Payment successfully added." });
                    }
                    catch (Exception ex)
                    {
                        dbTransaction.Rollback();
                        return Json(new { Flag = false, Msg = ex.Message });
                    }
                }

            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Msg = ex.Message });
            }
        }

        [CrmAuthorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult AgentPayment()
        {
            ViewBag.ClientList = new SelectList(_db.AgentInfos.ToList(), "Id", "AgentName");
            return View();
        }

        [CrmAuthorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult AgentPayment(ClientPaymentViewModel payment)
        {
            try
            {
                ModelState.Clear();
                var branchId = _db.ClientInfos.Where(x => x.AgentId == payment.CustomerId).Select(x => x.BranchId).FirstOrDefault()
                    ?? _db.BranchInfos.Where(x => x.BranchName == "Main").Select(x => x.Id).FirstOrDefault();
                payment.BranchId = branchId;

                payment.Channel = Channel.IsAgent;
                payment.Status = Status.Active;

                TryValidateModel(payment);
                if (!ModelState.IsValid) return Json(new { Flag = false, Msg = "Invalid payment info." });
                if (payment.PaymentAmount > payment.DueAmount)
                    return Json(new { Flag = false, Msg = "Payment amount cannot be greater than Due amount." });
                if (payment.PaymentAmount > payment.ServiceAmount)
                    return Json(new { Flag = false, Msg = "Payment amount cannot be greater than Service amount." });

                using (var dbTransaction = _db.Database.BeginTransaction())
                {
                    try
                    {
                        var clientPayment = new CustomerPayment
                        {
                            BranchId = payment.BranchId,
                            CustomerId = payment.CustomerId,
                            PaymentDate = payment.PaymentDate,
                            PaymentAmount = payment.PaymentAmount,
                            EntryDate = DateTime.Now,
                            Status = payment.Status,
                            Channel = payment.Channel,
                            UserType = UserType.IsAdmin,
                            EntryBy = _db.Users.First(x => x.UserName == User.Identity.Name).Id
                        };
                        _db.CustomerPayments.Add(clientPayment);
                        _db.SaveChanges();
                        dbTransaction.Commit();
                        return Json(new { Flag = true, Msg = "Payment successfully added." });
                    }
                    catch (Exception ex)
                    {
                        dbTransaction.Rollback();
                        return Json(new { Flag = false, Msg = ex.Message });
                    }
                }

            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Msg = ex.Message });
            }
        }

        [CrmAuthorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult SupplierPayment()
        {
            ViewBag.ClientList = new SelectList(_db.SuppliersInfos.ToList(), "Id", "SupplierName");
            return View();
        }

        [CrmAuthorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult SupplierPayment(ClientPaymentViewModel payment)
        {
            try
            {
                ModelState.Clear();
                var branchId = _db.ClientInfos.Where(x => x.SupplierId == payment.CustomerId).Select(x => x.BranchId).FirstOrDefault()
                    ?? _db.BranchInfos.Where(x => x.BranchName == "Main").Select(x => x.Id).FirstOrDefault();
                payment.BranchId = branchId;

                payment.Channel = Channel.IsSupplier;
                payment.Status = Status.Active;

                TryValidateModel(payment);
                if (!ModelState.IsValid) return Json(new { Flag = false, Msg = "Invalid payment info." });
                if (payment.PaymentAmount > payment.DueAmount)
                    return Json(new { Flag = false, Msg = "Payment amount cannot be greater than Due amount." });
                if (payment.PaymentAmount > payment.ServiceAmount)
                    return Json(new { Flag = false, Msg = "Payment amount cannot be greater than Service amount." });

                using (var dbTransaction = _db.Database.BeginTransaction())
                {
                    try
                    {
                        var clientPayment = new CustomerPayment
                        {
                            BranchId = payment.BranchId,
                            CustomerId = payment.CustomerId,
                            PaymentDate = payment.PaymentDate,
                            PaymentAmount = payment.PaymentAmount,
                            EntryDate = DateTime.Now,
                            Status = payment.Status,
                            Channel = payment.Channel,
                            UserType = UserType.IsAdmin,
                            EntryBy = _db.Users.First(x => x.UserName == User.Identity.Name).Id
                        };
                        _db.CustomerPayments.Add(clientPayment);
                        _db.SaveChanges();
                        dbTransaction.Commit();
                        return Json(new { Flag = true, Msg = "Payment successfully added." });
                    }
                    catch (Exception ex)
                    {
                        dbTransaction.Rollback();
                        return Json(new { Flag = false, Msg = ex.Message });
                    }
                }

            }
            catch (Exception ex)
            {

App.Web/Views/Billing/AgentPayment.cshtml
@model App.Web.Models.ClientPaymentViewModel
@{
    ViewBag.Title = "Agent Payments";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var options = new AjaxOptions
    {
        HttpMethod = "POST",
        OnSuccess = "OnSuccess",
        OnComplete = "OnComplete",
        OnFailure = "OnFailure"
    };
}
@section AdditionalStyles
{
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/custom.css" rel="stylesheet" />
}
<div class="card">
    <h6 class="card-header bg-primary">BILLING / AGENT PAYMENTS</h6>
    <div class="card-block">
        @using (Ajax.BeginForm("AgentPayment", "Billing", null, options, new { @class = "form-horizontal", @id = "agentPaymentForm" }))
        {
            <div class="card">
                <div class="card-block">
                    <div class="row">

                        <div class="col-md-6">
                            
                            <div class="form-group col-md-12">
                                @Html.Label("CustomerId", "Agents", htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                                <div class="col-sm-8">
                                    @Html.DropDownListFor(model => model.CustomerId, (SelectList) ViewBag.ClientList, "Select One", new {@class = "form-control select2"})
                                    @Html.ValidationMessageFor(model => model.CustomerId, "", new {@class = "text-danger"})
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group col-md-12">
                                @Html.LabelFor(model => model.ServiceAmount, htmlAttributes: new { @class = "control-label col-sm-6 text-md-right" })
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(model => model.ServiceAmount, null, new { @class = "form-control", @readonly = "readonly", @type = "number" })
                                    @Html.ValidationMessageFor(model => model.ServiceAmount, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group col-md-12">
                                @Html.LabelFor(model => model.PaidAmount, htmlAttributes: new { @class = "control-label col-sm-6 text-md-right" })
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(model => model.PaidAmount, null, new { @class = "form-control", @readonly = "readonly", @type = "number" })
                                    @Html.ValidationMessageFor(model => model.PaidAmount, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                @Html.LabelFor(model => model.DueAmount, htmlAttributes: new { @class = "control-label col-sm-6 text-md-right" })
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(model => model.DueAmount, null, new { @class = "form-control", @readonly = "readonly", @type = "number" })
                                    @Html.ValidationMessageFor(model => model.DueAmount, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>

            <div id="agentPaymentAdditional">

            </div>

        }
        <br />
        <table class="table table-bordered table-striped" id="clientPaymentInfoTable">
            <thead>
                <tr>
                    <th>Payment Made By</th>
                    <th>Payment Date</th>
                    <th>Payment Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="3" align="center">No matching record found.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/mvcfoolproof.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script>
        ReSelect2();
        PickDate();

        function ReValidate() {
            var form = $("#agentPaymentForm");
            form.removeData("validator");
            form.removeData("unobtrusiveValidation");
            $.validator.unobtrusive.parse("#agentPaymentForm");
        }

        function ClearFields() {
            $("#ServiceAmount").val('');
            $("#PaidAmount").val('');
            $("#DueAmount").val('');
            $("#PaymentDate").val('');
            $("#PaymentAmount").val('');
        }

        function ClearTableData() {
            $("#clientPaymentInfoTable tbody").html(
                '<tr>' +
                    '<td colspan="3" align="center">No matching record found.</td>' +
                '</tr>'
            );
        }

        function GetAgentPaymentInfo(value) {
            if (value !== "") {
                $.get("@Url.Action("GetServiceChargeInfoForAgent", "Billing")", { agentId: value }, function (resp) {
                    if (resp.Flag) {
                        $("#ServiceAmount").val(resp.TotalServiceCharge);
                        $("#PaidAmount").val(resp.TotalPaid);
                        $("#DueAmount").val(resp.Due);
                    }
                    if (resp.IsDueExist) {
                        $(".pickDate").datepicker("destroy");
                        $.get("@Url.Action("GetPaymentFields","Billing")", function (html) {
                            if (html === null) return;
                            $("#agentPaymentAdditional").html(html).slideDown(500);
                            $("#paymentFields").hide();
                            PickDate();
                            ReValidate();
                        });
                    } else {
                        $("#agentPaymentAdditional").empty().slideDown(500);
                    }

                    var tbody = $("#clientPaymentInfoTable tbody");
                    if (resp.Payments !== null) {
                        tbody.empty();
                        $.each(resp.Payments, function (index, payment) {
                            tbody.append(
                                '<tr>' +
                                    '<td>' + payment.PaymnentMadeBy + '</td>' +
                                    '<td>' + payment.PaymentDate + '</td>' +
                                    '<td>' + payment.PaymentAmount + '</td>' +
                                '</tr>'
                            );
                        });
                        tbody.append(
                            '<tr>' +
                                '<td colspan="2" align="right">Total:</td>' +
                                '<td>' + resp.TotalPaid + '</td>' +
                            '</tr>'
                        );
                    }
                    else {
                        ClearTableData();
                    }
                });
                return true;
            }
            return false;
        }

        function OnBegin() {}

        function OnComplete() {}

        function OnSuccess(resp) {
            console.log(resp);
            if (resp.Flag) {
                toastr.success(resp.Msg, 'Success!');
            }
            else
            {
                toastr.error(resp.Msg, 'Error!');
            }
            var value = $("#CustomerId").val();
            ClearFields();
            if (!GetAgentPaymentInfo(value)) $("#agentPaymentAdditional").empty();
        }

        function OnFailure() {
            //alert('On Failure');
            console.log('On Failure');
        }

        $("#CustomerId").change(function () {
            var value = $(this).val();

            ClearFields();
            ClearTableData();

            if (!GetAgentPaymentInfo(value)) $("#agentPaymentAdditional").empty();
        });

        $("body").on("click", "#addPaymentBtn", function () {
            $("#paymentFields").slideToggle(500);
        });
    </script>
}

App.Web/Views/Billing/ClientPayment.cshtml
@model App.Web.Models.ClientPaymentViewModel
@{
    ViewBag.Title = "Client Payment";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var options = new AjaxOptions
    {
        HttpMethod = "POST",
        OnSuccess = "OnSuccess",
        OnComplete = "OnComplete",
        OnFailure = "OnFailure"
    };
}
@section AdditionalStyles
{
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/custom.css" rel="stylesheet" />
}
<div class="card">
    <h6 class="card-header bg-primary">BILLING / CLIENT PAYMENTS</h6>
    <div class="card-block">
        @using (Ajax.BeginForm("ClientPayment", "Billing", null, options, new { @class = "form-horizontal", @id = "clientPaymentForm" }))
        {
            <div class="card">
                <div class="card-block">
                    <div class="row">

                        <div class="col-md-6">
                            @if (User.IsInRole("Admin"))
                            {
                                <div class="form-group col-md-12">
                                    @Html.LabelFor(model => model.BranchId, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                                    <div class="col-sm-8">
                                        @Html.DropDownListFor(model => model.BranchId, (SelectList)ViewBag.BranchList, "Select One", new { @class = "form-control select2" })
                                        @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            }
                            <div class="form-group col-md-12">
                                @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                                <div class="col-sm-8">
                                    @Html.DropDownListFor(model => model.CustomerId, (SelectList)ViewBag.ClientList, "Select One", new { @class = "form-control select2" })
                                    @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group col-md-12">
                                @Html.LabelFor(model => model.ServiceAmount, htmlAttributes: new { @class = "control-label col-sm-6 text-md-right" })
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(model => model.ServiceAmount, null, new { @class = "form-control", @readonly = "readonly", @type = "number" })
                                    @Html.ValidationMessageFor(model => model.ServiceAmount, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group col-md-12">
                                @Html.LabelFor(model => model.PaidAmount, htmlAttributes: new { @class = "control-label col-sm-6 text-md-right" })
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(model => model.PaidAmount, null, new { @class = "form-control", @readonly = "readonly", @type = "number" })
                                    @Html.ValidationMessageFor(model => model.PaidAmount, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                @Html.LabelFor(model => model.DueAmount, htmlAttributes: new { @class = "control-label col-sm-6 text-md-right" })
                                <div class="col-sm-6">
                                    @Html.TextBoxFor(model => model.DueAmount, null, new { @class = "form-control", @readonly = "readonly", @type = "number" })
                                    @Html.ValidationMessageFor(model => model.DueAmount, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>

            <div id="clientPaymentAdditional">

            </div>

        }
        <br />
        <table class="table table-bordered table-striped" id="clientPaymentInfoTable">
            <thead>
                <tr>
                    <th>Payment Made By</th>
                    <th>Payment Date</th>
                    <th>Payment Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="3" align="center">No matching record found.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/mvcfoolproof.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script>
        ReSelect2();
        PickDate();

        function ReValidate() {
            var form = $("#clientPaymentForm");
            form.removeData("validator");
            form.removeData("unobtrusiveValidation");
            $.validator.unobtrusive.parse("#clientPaymentForm");
        }

        function ClearFields() {
            $("#ServiceAmount").val('');
            $("#PaidAmount").val('');
            $("#DueAmount").val('');
            $("#PaymentDate").val('');
            $("#PaymentAmount").val('');
        }

        function ClearTableData() {
            $("#clientPaymentInfoTable tbody").html(
                '<tr>' +
                    '<td colspan="3" align="center">No matching record found.</td>' +
                '</tr>'
            );
        }

        function GetClientPaymentInfo(value) {
            if (value !== "") {
                $.get("@Url.Action("GetServiceChargeInfo", "Billing")", { customerId: value }, function (resp) {
                    if (resp.Flag) {
                        $("#ServiceAmount").val(resp.TotalServiceCharge);
                        $("#PaidAmount").val(resp.TotalPaid);
                        $("#DueAmount").val(resp.Due);
                    }
                    if (resp.IsDueExist) {
                        $(".pickDate").datepicker("destroy");
                        $.get("@Url.Action("GetPaymentFields","Billing")", function (html) {
                            if (html === null) return;
                            $("#clientPaymentAdditional").html(html).slideDown(500);
                            $("#paymentFields").hide();
                            PickDate();
                            ReValidate();
                        });
                    } else {
                        $("#clientPaymentAdditional").empty().slideDown(500);
                    }

                    var tbody = $("#clientPaymentInfoTable tbody");
                    if (resp.Payments !== null) {
                        tbody.empty();
                        $.each(resp.Payments, function (index, payment) {
                            tbody.append(
                                '<tr>' +
                                    '<td>' + payment.PaymnentMadeBy + '</td>' +
                                    '<td>' + payment.PaymentDate + '</td>' +
                                    '<td>' + payment.PaymentAmount + '</td>' +
                                '</tr>'
                            );
                        });
                        tbody.append(
                            '<tr>' +
                                '<td colspan="2" align="right">Total:</td>' +
                                '<td>' + resp.TotalPaid + '</td>' +
                            '</tr>'
                        );
                    }
                    else {
                        ClearTableData();
                    }
                });
                return true;
            }
            return false;
        }

        function OnBegin() {
            //alert('On Begin');
            console.log('On Begin');
        }

        function OnComplete() {
            //alert('On Completed');
            //console.log('On Completed');
        }

        function OnSuccess(resp) {
            console.log(resp);
            if (resp.Flag) {
                toastr.success(resp.Msg, 'Success!');
            }
            else
            {
                toastr.error(resp.Msg, 'Error!');
            }
            var value = $("#CustomerId").val();
            ClearFields();
            if (!GetClientPaymentInfo(value)) $("#clientPaymentAdditional").empty();
        }

        function OnFailure() {
            //alert('On Failure');
            console.log('On Failure');
        }

        $("#BranchId").change(function () {
            var value = $(this).val();

            ClearFields();
            ClearTableData();
            //$("#clientPaymentAdditional").empty();

            if (value !== "") {
                $.get("@Url.Action("GetClientsBranchWise", "Billing")", { branchId: value }, function (resp) {
                    if (resp.Flag) {
                        $("#CustomerId").empty().html("<option value>Select One</option>");
                        $.each(resp.Clients,
                            function (key, item) {
                                $("<option>").attr("value", item.Value).html(item.Text).appendTo("#CustomerId");
                            });
                    } else {
                        $("#CustomerId").empty().html("<option value>Select One</option>");
                        $("#clientPaymentAdditional").empty();
                    }
                });
                return;
            }
            $("#clientPaymentAdditional").empty();
        });

        $("#CustomerId").change(function () {
            var value = $(this).val();

            ClearFields();
            ClearTableData();

            if (!GetClientPaymentInfo(value)) $("#clientPaymentAdditional").empty();
        });

        $("body").on("click", "#addPaymentBtn", function () {
            $("#paymentFields").slideToggle(500);
        });
    </script>
}