App.Web/Controllers/ServicesController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using App.Entity.Models;
using App.Web.Context;
using App.Web.Helper;
using EntityFramework.Extensions;

namespace App.Web.Controllers
{
    [CrmAuthorize(Roles = "Admin")]
    [CrmPermission]
    public class ServicesController : Controller
    {

        #region Private Zone

        private readonly CrmDbContext _db;

        #endregion

        public ServicesController()
        {
            _db = new CrmDbContext();
        }

        // GET: Services
        public ActionResult Index()
        {
            return View();
        }

        // GET: Services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["Toastr"] = Toastr.BadRequest;
                return RedirectToAction("Index");
            }
            var serviceInfo = _db.ServiceInfos.Find(id);

            if (serviceInfo != null) return View(serviceInfo);

            TempData["Toastr"] = Toastr.HttpNotFound;
            return RedirectToAction("Index");
        }

        // GET: Services/Create
        public ActionResult Create()
        {
            ViewBag.Status = Common.ToSelectList<Status>();
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ServiceName,Description,Status")] ServiceInfo serviceInfo)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    ModelState.Clear();
                    serviceInfo.ServiceId = string.Format("DI-{0:000000}", _db.ServiceInfos.Count() + 1);
                    serviceInfo.EntryBy = _db.Users.First(x => x.UserName == User.Identity.Name).Id;
                    serviceInfo.EntryDate = DateTime.Now;
                    TryValidateModel(serviceInfo);
                    if (ModelState.IsValid)
                    {
                        _db.ServiceInfos.Add(serviceInfo);
                        _db.SaveChanges();

                        dbTransaction.Commit();
                        TempData["Toastr"] = Toastr.Added;

                        return RedirectToAction("Index");
                    }
                    dbTransaction.Rollback();
                    return View(serviceInfo);
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
                finally
                {
                    ViewBag.Status = Common.ToSelectList<Status>();
                }

            }
        }

        // GET: Services/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    TempData["Toastr"] = Toastr.BadRequest;
                    return RedirectToAction("Index");
                }
                var service = _db.ServiceInfos.Find(id);
                if (service == null)
                {
                    TempData["Toastr"] = Toastr.HttpNotFound;
                    return RedirectToAction("Index");
                }
                ViewBag.StatusList = Common.ToSelectList<Status>(service.Status);

                return View(service);
            }
            catch (Exception ex)
            {
                TempData["Toastr"] = Toastr.DbError(ex.Message);
                return RedirectToAction("Index");
            }
        }

        // POST: Services/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ServiceName,Description,Status")] ServiceInfo service, int? id)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    if (id == null)
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }
                    if (_db.ServiceInfos.Count(x => x.Id == id) < 1)
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }
                    var serviceInfo = _db.ServiceInfos.Single(x => x.Id == id);
                    if (serviceInfo == null)
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }

                    ModelState.Clear();
                    service.ServiceId = serviceInfo.ServiceId;
                    service.EntryBy = serviceInfo.EntryBy;
                    service.EntryDate = serviceInfo.EntryDate;
                    service.DelStatus = serviceInfo.DelStatus;

                    TryValidateModel(service);

                    if (!ModelState.IsValid) return View(service);

                    _db.ServiceInfos
                        .Where(x => x.Id == id)
                        .Update(u => new ServiceInfo
                        {
                            ServiceName = service.ServiceName,
                            Description = service.Description,
                            Status = service.Status
                        });
                    dbTransaction.Commit();

                    TempData["Toastr"] = Toastr.Updated;
                    return RedirectToAction("Index");

                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
                finally
                {
                    ViewBag.StatusList = Common.ToSelectList<Status>(service.Status);
                }
            }
        }

        //// GET: Services/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ServiceInfo serviceInfo = _db.ServiceInfos.Find(id);
        //    if (serviceInfo == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(serviceInfo);
        //}

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    if (id == null)
                    {
                        TempData["Toastr"] = Toastr.BadRequest;
                        return RedirectToAction("Index");
                    }
                    var service = _db.ServiceInfos.Find(id);
                    if (service == null)
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }
                    _db.ServiceInfos.Remove(service);
                    _db.SaveChanges();
                    dbTransaction.Commit();

                    TempData["Toastr"] = Toastr.Deleted;
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
            }
        }

        [HttpPost]
        public ActionResult IsServiceAvailable(string serviceName, int? id)
        {
            try
            {
                var flag = true;
                //create mode
                if (id == null)
                {
                    flag = !_db.ServiceInfos.Any(x => x.ServiceName == serviceName);
                }
                // edit mode
                else
                {
                    var service = _db.ServiceInfos.Find(id);
                    if (service == null) return Json(false, JsonRequestBehavior.AllowGet);
                    if (service.ServiceName != serviceName) flag = !_db.ServiceInfos.Any(x => x.ServiceName == serviceName);
                }
                return Json(flag, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App.Web/Views/Services/Create.cshtml
@model App.Entity.Models.ServiceInfo

@{
    ViewBag.Title = "Add New Service";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h6 class="card-header bg-primary">SERVICES / ADD NEW</h6>
    <div class="card-block">
        <div class="row">
            @using (Html.BeginForm("Create", "Services", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <div class="form-group offset-md-2 col-md-8">
                        @Html.LabelFor(model => model.ServiceName, htmlAttributes: new { @class = "control-label col-sm-3 text-md-right" })
                        <div class="col-sm-6">
                            @Html.EditorFor(model => model.ServiceName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ServiceName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group offset-md-2 col-md-8">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-sm-3 text-md-right" })
                        <div class="col-sm-6">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group offset-md-2 col-md-8">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-sm-3 text-md-right" })
                        <div class="col-sm-6">
                            @Html.DropDownListFor(model => model.Status, (SelectList)ViewBag.StatusList, "Select One", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group offset-md-2 col-md-8">
                        <div class="offset-sm-6 col-sm-3">
                            <button type="submit" class="btn btn-success pull-right"> <span class="fa fa-plus"></span> Add New </button>
                        </div>
                    </div>
                </div>
            }
            <div class="col-md-3">
                <a href="@Url.Action("Index")" class="btn btn-info"> <span class="fa fa-chevron-left"></span> Back to List</a>
            </div>

        </div>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

App.Web/Views/Services/Details.cshtml
@model App.Entity.Models.ServiceInfo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h6 class="card-header bg-primary">SERVICE / DETAILS</h6>
    <div class="card-block">
        <div class="row">
            <div class="col-md-12">
                <h5>
                    SERVICE NAME: @Model.ServiceName.ToUpper()
                    <a href="@Url.Action("Edit", new { id = Model.Id })" class="btn btn-primary btn-sm"> <span class="fa fa-edit"></span> Edit</a>
                </h5>
                <br />
                <table class="table table-striped m-md-b-0">

                    <tr>
                        <th width="150">@Html.DisplayNameFor(m => m.ServiceId)</th>
                        <td>@Model.ServiceId</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.Description)</th>
                        <td>@(string.IsNullOrWhiteSpace(Model.Description)?"No description added.":Model.Description)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.Status)</th>
                        <td>@Model.Status</td>
                    </tr>
                </table>
            </div>
        </div>
        <br />
        <div class="col-md-3">
            <a href="@Url.Action("Index")" class="btn btn-info"> <span class="fa fa-chevron-left"></span> Back to List</a>
        </div>
    </div>

</div>

App.Web/Views/Services/Edit.cshtml
@model App.Entity.Models.ServiceInfo

@{
    ViewBag.Title = "Edit Service";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h6 class="card-header bg-primary">SERVICES / EDIT</h6>
    <div class="card-block">
        <div class="row">
            @using (Html.BeginForm("Edit", "Services", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Id)
                <div class="form-horizontal">

                    <div class="form-group offset-md-2 col-md-8">
                        @Html.LabelFor(model => model.ServiceName, htmlAttributes: new { @class = "control-label col-sm-3 text-md-right" })
                        <div class="col-sm-6">
                            @Html.EditorFor(model => model.ServiceName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ServiceName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group offset-md-2 col-md-8">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-sm-3 text-md-right" })
                        <div class="col-sm-6">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" } )
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group offset-md-2 col-md-8">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-sm-3 text-md-right" })
                        <div class="col-sm-6">
                            @Html.DropDownListFor(model => model.Status, (SelectList)ViewBag.StatusList, "Select One", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group offset-md-2 col-md-8">
                        <div class="offset-sm-6 col-sm-3">
                            <button type="submit" class="btn btn-success pull-right"> <span class="fa fa-plus"></span> Save Changes </button>
                        </div>
                    </div>
                </div>
            }
            <div class="col-md-3">
                <a href="@Url.Action("Index")" class="btn btn-info"> <span class="fa fa-chevron-left"></span> Back to List</a>
            </div>

        </div>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

App.Web/Views/Services/Index.cshtml
@using App.Entity.Models
@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section AdditionalStyles
{
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/MvcGridPagination.css" rel="stylesheet" />
    <link href="~/vendor/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
}

@using (Html.BeginForm("Delete", "Services", FormMethod.Post, new { @style = "display:none;", @id = "deleteForm" }))
{
    @Html.Hidden("Id")
}
<div class="card">
    <h6 class="card-header bg-primary">SERVICES / LIST</h6>
    <div class="card-block">
        <div class="row">
            <div class="col-md-6">
                <a href="@Url.Action("Create")" class="btn btn-info"> <span class="fa fa-plus"></span> Create New</a>
                <button class="btn btn-outline-info refreshBtn"><span class="fa fa-refresh"></span> Refresh</button>
            </div>
            <br /><br /> <br />
            <div class="col-md-12">
                @*<table class="table table-striped table-bordered m-md-b-0" id="branchTable"></table>*@
                @Html.Partial("~/Views/Shared/_MVCGridToolbar.cshtml", new MVCGridToolbarModel()
                {
                    MVCGridName = "serviceTable",
                    PageSize = true,
                    //ColumnVisibility = true,
                    GlobalSearch = true
                })
                @Html.MVCGrid("serviceTable")
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/MVCGridHandler.axd/script.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/Scripts/index.js"></script>
    <script>
        @if (TempData["Toastr"] != null)
        {
            @Html.Raw(TempData["Toastr"])
        }

        $(".refreshBtn").click(function() {
            MVCGrid.reloadGrid('serviceTable');
        });
    </script>
}