App.Web/Controllers/BranchController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using App.Entity.Models;
using App.Web.Context;
using App.Web.Helper;
using EntityFramework.Extensions;

namespace App.Web.Controllers
{
    [CrmAuthorize(Roles = "Admin")]
    [CrmPermission]
    public class BranchController : Controller
    {
        #region Private Zone
        private readonly CrmDbContext _db;
        #endregion
        
        public BranchController()
        {
            _db = new CrmDbContext();
        }
        // GET: Branch
        public ActionResult Index()
        {
            return View();
        }

        // GET: Branch/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    TempData["Toastr"] = Toastr.BadRequest;
                    return RedirectToAction("Index");
                }
                var branchInfo = _db.BranchInfos.Find(id);
                if (branchInfo != null) return View(branchInfo);

                TempData["Toastr"] = Toastr.HttpNotFound;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Toastr"] = Toastr.DbError(ex.Message);
                return RedirectToAction("Index");
            }

        }

        // GET: Branch/Create
        public ActionResult Create()
        {
            ViewBag.StatusList = Common.ToSelectList<Status>();
            return View();
        }

        // POST: Branch/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BranchName,BranchCode,Status")] BranchInfo branchInfo)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    ModelState.Clear();
                    branchInfo.BranchId = string.Format("BI-{0:000000}", _db.BranchInfos.Count() + 1);
                    branchInfo.EntryBy = _db.Users.First(x => x.UserName == User.Identity.Name).Id;
                    branchInfo.EntryDate = DateTime.Now;
                    TryValidateModel(branchInfo);
                    if (ModelState.IsValid)
                    {
                        _db.BranchInfos.Add(branchInfo);
                        _db.SaveChanges();

                        dbTransaction.Commit();
                        TempData["Toastr"] = Toastr.Added;

                        return RedirectToAction("Index");
                    }
                    dbTransaction.Rollback();
                    return View(branchInfo);
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
                finally
                {
                    ViewBag.Status = Common.ToSelectList<Status>();
                }

            }
        }

        // GET: Branch/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    TempData["Toastr"] = Toastr.BadRequest;
                    return RedirectToAction("Index");
                }
                var branchInfo = _db.BranchInfos.Find(id);
                if (branchInfo == null)
                {
                    TempData["Toastr"] = Toastr.HttpNotFound;
                    return RedirectToAction("Index");
                }
                ViewBag.StatusList = Common.ToSelectList<Status>(branchInfo.Status);

                return View(branchInfo);
            }
            catch (Exception ex)
            {
                TempData["Toastr"] = Toastr.DbError(ex.Message);
                return RedirectToAction("Index");
            }
        }

        // POST: Branch/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BranchName,BranchCode,Status")] BranchInfo branchInfo, int? id)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    if (id == null)
                    {
                        TempData["Toastr"] = Toastr.BadRequest;
                        return RedirectToAction("Index");
                    }
                    if (_db.BranchInfos.Count(x => x.Id == id) < 1)
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }
                    var branch = _db.BranchInfos.Single(x => x.Id == id);

                    ModelState.Clear();

                    branchInfo.BranchId = branch.BranchId;
                    branchInfo.DelStatus = branch.DelStatus;
                    branchInfo.EntryBy = branch.EntryBy;
                    branchInfo.EntryDate = branch.EntryDate;

                    TryValidateModel(branchInfo);
                    if (!ModelState.IsValid) return View(branchInfo);

                    _db.BranchInfos
                        .Where(x => x.Id == id)
                        .Update( u => new BranchInfo {
                            BranchName = branchInfo.BranchName,
                            BranchCode = branchInfo.BranchCode,
                            Status = branchInfo.Status
                        });
                    dbTransaction.Commit();

                    TempData["Toastr"] = Toastr.Updated;
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
                finally
                {
                    ViewBag.StatusList = Common.ToSelectList<Status>(branchInfo.Status);
                }
            }
        }

        //// GET: Branch/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    BranchInfo branchInfo = _db.BranchInfos.Find(id);
        //    if (branchInfo == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(branchInfo);
        //}

        // POST: Branch/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    if (id == null)
                    {
                        TempData["Toastr"] = Toastr.BadRequest;
                        return RedirectToAction("Index");
                    }
                    var branchInfo = _db.BranchInfos.Find(id);
                    if (branchInfo == null)
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }
                    _db.BranchInfos.Remove(branchInfo);
                    _db.SaveChanges();
                    dbTransaction.Commit();
                    TempData["Toastr"] = Toastr.Deleted;
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App.Web/Controllers/CountryController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using App.Entity.Models;
using App.Web.Context;
using App.Web.Helper;
using EntityFramework.Extensions;

namespace App.Web.Controllers
{
    [CrmAuthorize(Roles = "Admin")]
    [CrmPermission]
    public class CountryController : Controller
    {
        #region Private Zone
        private readonly CrmDbContext _db;
        #endregion

        public CountryController()
        {
            _db = new CrmDbContext();
        }
        // GET: Country
        public ActionResult Index()
        {
            return View();
        }

        // GET: Country/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    TempData["Toastr"] = Toastr.BadRequest;
                    return RedirectToAction("Index");
                }
                var country = _db.Countries.Find(id);
                if (country != null) return View(country);

                TempData["Toastr"] = Toastr.HttpNotFound;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Toastr"] = Toastr.DbError(ex.Message);
                return RedirectToAction("Index");
            }

        }

        // GET: Country/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Country/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CountryName,CountryCode,DelStatus")] Country country)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    ModelState.Clear();
                    country.EntryBy = _db.Users.First(x => x.UserName == User.Identity.Name).Id;
                    country.EntryDate = DateTime.Now;
                    TryValidateModel(country);
                    if (ModelState.IsValid)
                    {
                        _db.Countries.Add(country);
                        _db.SaveChanges();

                        dbTransaction.Commit();
                        TempData["Toastr"] = Toastr.Added;

                        return RedirectToAction("Index");
                    }
                    dbTransaction.Rollback();
                    return View(country);
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
                finally
                {
                    ViewBag.Status = Common.ToSelectList<Status>();
                }

            }
        }

        // GET: Country/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    TempData["Toastr"] = Toastr.BadRequest;
                    return RedirectToAction("Index");
                }
                var country = _db.Countries.Find(id);
                if (country != null) return View(country);

                TempData["Toastr"] = Toastr.HttpNotFound;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Toastr"] = Toastr.DbError(ex.Message);
                return RedirectToAction("Index");
            }
        }

        // POST: Country/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CountryName,CountryCode,DelStatus")] Country country, int? id)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    if (id == null)
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }
                    if (!_db.Countries.Any(x=>x.Id == id))
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }
                    var data = _db.Countries.Single(x => x.Id == id);

                    ModelState.Clear();

                    country.DelStatus = data.DelStatus;
                    country.EntryBy = data.EntryBy;
                    country.EntryDate = data.EntryDate;

                    TryValidateModel(country);
                    if (!ModelState.IsValid) return View(country);

                    _db.Countries
                        .Where(x => x.Id == id)
                        .Update( u => new Country {
                            CountryName = country.CountryName,
                            CountryCode = country.CountryCode
                        });
                    dbTransaction.Commit();

                    TempData["Toastr"] = Toastr.Updated;
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
            }
        }

        //// GET: Country/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    BranchInfo branchInfo = _db.BranchInfos.Find(id);
        //    if (branchInfo == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(branchInfo);
        //}

        // POST: Country/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? countryId)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    if (countryId == null)
                    {
                        TempData["Toastr"] = Toastr.BadRequest;
                        return RedirectToAction("Index");
                    }
                    if (!_db.Countries.Any(x=>x.Id == countryId))
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }

                    _db.Countries
                        .Where(x => x.Id == countryId)
                        .Update(u => new Country
                        {
                            DelStatus = true
                        });
                    dbTransaction.Commit();
                    TempData["Toastr"] = Toastr.Deleted;
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App.Web/Views/Country/Create.cshtml
@model App.Entity.Models.Country

@{
    ViewBag.Title = "Add New Country";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h6 class="card-header bg-primary">COUNTRY / ADD NEW</h6>
    <div class="card-block">
        <div class="row">
            @using (Html.BeginForm("Create", "Country", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <div class="form-group offset-md-2 col-md-8">
                        @Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-sm-3 text-md-right" })
                        <div class="col-sm-6">
                            @Html.EditorFor(model => model.CountryName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group offset-md-2 col-md-8">
                        @Html.LabelFor(model => model.CountryCode, htmlAttributes: new { @class = "control-label col-sm-3 text-md-right" })
                        <div class="col-sm-6">
                            @Html.EditorFor(model => model.CountryCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CountryCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group offset-md-2 col-md-8">
                        <div class="offset-sm-6 col-sm-3">
                            <button type="submit" class="btn btn-success pull-right"> <span class="fa fa-plus"></span> Add New </button>
                        </div>
                    </div>
                </div>
            }
            <div class="col-md-3">
                <a href="@Url.Action("Index")" class="btn btn-info"> <span class="fa fa-chevron-left"></span> Back to List</a>
            </div>

        </div>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

App.Web/Views/Country/Details.cshtml
@model App.Entity.Models.Country

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h6 class="card-header bg-primary">COUNTRY / DETAILS</h6>
    <div class="card-block">
        <div class="row">
            <div class="col-md-12">
                <h5>
                    COUNTRY NAME: @Model.CountryName.ToUpper()
                    <a href="@Url.Action("Edit", new { id = Model.CountryId })" class="btn btn-primary btn-sm"> <span class="fa fa-edit"></span> Edit</a>
                </h5>
                <br />
                <table class="table table-striped m-md-b-0">

                    <tr>
                        <th width="150">@Html.DisplayNameFor(m => m.CountryCode)</th>
                        <td>@Model.CountryCode</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.DelStatus)</th>
                        <td>@Model.DelStatus ? "Deleted" : "Not Deleted"</td>
                    </tr>
                </table>
            </div>
        </div>
        <br />
        <div class="col-md-3">
            <a href="@Url.Action("Index")" class="btn btn-info"> <span class="fa fa-chevron-left"></span> Back to List</a>
        </div>
    </div>

</div>

App.Web/Views/Country/Edit.cshtml
@model App.Entity.Models.Country

@{
    ViewBag.Title = "Edit Country";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section AdditionalStyles
{
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet" />
}

<div class="card">
    <h6 class="card-header bg-primary">COUNTRY / EDIT</h6>
    <div class="card-block">
        <div class="row">
            @using (Html.BeginForm("Edit", "Country", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Id)
                <div class="form-horizontal">

                    <div class="form-group offset-md-2 col-md-8">
                        @Html.LabelFor(model => model.CountryName, htmlAttributes: new { @class = "control-label col-sm-3 text-md-right" })
                        <div class="col-sm-6">
                            @Html.EditorFor(model => model.CountryName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group offset-md-2 col-md-8">
                        @Html.LabelFor(model => model.CountryCode, htmlAttributes: new { @class = "control-label col-sm-3 text-md-right" })
                        <div class="col-sm-6">
                            @Html.EditorFor(model => model.CountryCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CountryCode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group offset-md-2 col-md-8">
                        <div class="offset-sm-6 col-sm-3">
                            <button type="submit" class="btn btn-success pull-right"> <span class="fa fa-plus"></span> Save Changes </button>
                        </div>
                    </div>
                </div>
            }
            <div class="col-md-3">
                <a href="@Url.Action("Index")" class="btn btn-info"> <span class="fa fa-chevron-left"></span> Back to List</a>
            </div>

        </div>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script>
        @if (TempData["Toastr"]!=null)
        {
            @Html.Raw(TempData["Toastr"])
        }
    </script>
}

App.Web/Views/Country/Index.cshtml
@using App.Entity.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section AdditionalStyles
{
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/MvcGridPagination.css" rel="stylesheet" />
    <link href="~/vendor/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
}

@using (Html.BeginForm("Delete", "Branch", FormMethod.Post, new { @style = "display:none;", @id = "deleteForm" }))
{
    @Html.Hidden("Id")
}
<div class="card">
    <h6 class="card-header bg-primary">COUNTRY / LIST</h6>
    <div class="card-block">
        <div class="row">
            <div class="col-md-6">
                <a href="@Url.Action("Create")" class="btn btn-info"> <span class="fa fa-plus"></span> Create New</a>
                <button class="btn btn-outline-info refreshBtn"><span class="fa fa-refresh"></span> Refresh</button>
            </div>
            <br /><br /> <br />
            <div class="col-md-12">
                @*<table class="table table-striped table-bordered m-md-b-0" id="countryTable"></table>*@
                @Html.Partial("~/Views/Shared/_MVCGridToolbar.cshtml", new MVCGridToolbarModel()
                {
                    MVCGridName = "countryTable",
                    PageSize = true,
                    //ColumnVisibility = true,
                    GlobalSearch = true
                })
                @Html.MVCGrid("countryTable")
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/MVCGridHandler.axd/script.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/Scripts/index.js"></script>
    <script>
        @if (TempData["Toastr"] != null)
        {
            @Html.Raw(TempData["Toastr"])
        }

        $(".refreshBtn").click(function() {
            MVCGrid.reloadGrid('countryTable');
        });
    </script>
}