App.Web/Models/DepositViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using App.Entity.Models;

namespace App.Web.Models
{
    public class DepositViewModel
    {
        public DepositViewModel()
        {
            Date = DateTime.Now;
        }

        public int Id { get; set; }

        [Display(Name = "Account Id")]
        public int AccountId { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime Date { get; set; }

        [Required]
        [Display(Name = "Payer Type")]
        public PayerType PayerType { get; set; }

        [Display(Name = "Payer")]
        public int? PayerId { get; set; }

        [Range(0.01, double.MaxValue, ErrorMessage = "Amount should be greater than 0.")]
        public decimal Amount { get; set; }

        [Display(Name = "Payment Method")]
        public int MethodId { get; set; }
        
        [Required]
        public string Description { get; set; }
    }
}

App.Web/Controllers/DepositsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using App.Entity.Models;
using App.Web.Context;
using App.Web.Helper;
using App.Web.Models;
using EntityFramework.Extensions;

namespace App.Web.Controllers
{
    [CrmAuthorize(Roles = "Admin")]
    [CrmPermission]
    public class DepositsController : Controller
    {
        #region Private Zone

        private readonly CrmDbContext _db;

        #endregion

        public DepositsController()
        {
            _db = new CrmDbContext();
        }
        // GET: Deposits
        public ActionResult Index()
        {
            return View();
        }

        // GET: Deposits/Details/5
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["Toastr"] = Toastr.BadRequest;
                return RedirectToAction("Index");
            }
            var transaction = _db.TransactionsInfos.Find(id);

            if (transaction != null) return View(transaction);

            TempData["Toastr"] = Toastr.HttpNotFound;
            return RedirectToAction("Index");
        }

        // GET: Deposits/Create
        public ActionResult Create()
        {
            ViewBag.Accounts = new SelectList(_db.BankAccounts.ToList(), "Id", "AccountName");
            ViewBag.PayerTypes = Common.ToSelectList<PayerType>();
            ViewBag.PaymentMethods = new SelectList(_db.PaymentMethods.ToList(), "Id", "MethodName");
            return View();
        }

        // POST: Deposits/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AccountId,Date,PayerType,Amount,MethodId,PayerId,Description")] DepositViewModel deposit)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    if (!ModelState.IsValid) return View(deposit);
                    ModelState.Clear();

                    var transaction = new TransactionsInfo();
                    transaction.TransactionId = string.Format("DI-{0:000000}", _db.TransactionsInfos.Count(x => x.TransactionType == TransactionType.Deposit || x.TransactionType == TransactionType.Transfer) + 1);
                    transaction.TransactionType = TransactionType.Deposit;
                    transaction.Date = deposit.Date;
                    transaction.AccountTo = deposit.AccountId;
                    transaction.PayerType = deposit.PayerType;
                    transaction.PayerId = deposit.PayerId;
                    transaction.Amount = deposit.Amount;
                    transaction.MethodId = deposit.MethodId;
                    transaction.Description = deposit.Description;

                    _db.TransactionsInfos.Add(transaction);
                    if (_db.SaveChanges() > 0) _db.UpdateBalance(_db.BankAccounts.Find(deposit.AccountId), (double) deposit.Amount);

                    dbTransaction.Commit();
                    TempData["Toastr"] = Toastr.Added;

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
                finally
                {
                    ViewBag.Accounts = new SelectList(_db.BankAccounts.ToList(), "Id", "AccountName");
                    ViewBag.PayerTypes = Common.ToSelectList<PayerType>();
                    ViewBag.PaymentMethods = new SelectList(_db.PaymentMethods.ToList(), "Id", "MethodName");
                }
            }
        }

        // GET: Deposits/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    TempData["Toastr"] = Toastr.BadRequest;
                    return RedirectToAction("Index");
                }
                var transactionsInfo = _db.TransactionsInfos.Find(id);
                if (transactionsInfo == null)
                {
                    TempData["Toastr"] = Toastr.HttpNotFound;
                    return RedirectToAction("Index");
                }
                var deposit = new DepositViewModel();
                deposit.Id = transactionsInfo.Id;
                // ReSharper disable once PossibleInvalidOperationException
                deposit.Date = (DateTime)transactionsInfo.Date;
                // ReSharper disable once PossibleInvalidOperationException
                deposit.AccountId = (int)transactionsInfo.AccountTo;
                // ReSharper disable once PossibleInvalidOperationException
                deposit.PayerType = (PayerType)transactionsInfo.PayerType;
                deposit.PayerId = transactionsInfo.PayerId;
                deposit.Amount = transactionsInfo.Amount;
                deposit.MethodId = transactionsInfo.MethodId;
                deposit.Description = transactionsInfo.Description;

                ViewBag.Accounts = new SelectList(_db.BankAccounts.ToList(), "Id", "AccountName",deposit.AccountId);
                ViewBag.PayerTypes = Common.ToSelectList<PayerType>(deposit.PayerType);
                ViewBag.PaymentMethods = new SelectList(_db.PaymentMethods.ToList(), "Id", "MethodName",deposit.MethodId);

                return View(deposit);
            }
            catch (Exception ex)
            {
                TempData["Toastr"] = Toastr.DbError(ex.Message);
                return RedirectToAction("Index");
            }
        }

        // POST: Deposits/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AccountId,Date,PayerType,Amount,MethodId,PayerId,Description")] DepositViewModel deposit, int? id)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    if (id == null)
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }

                    if (!_db.TransactionsInfos.Any(x => x.Id == id))
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }

                    if (!ModelState.IsValid) return View(deposit);
                    var count = _db.TransactionsInfos
                        .Where(x => x.Id == id)
                        .Update(u => new TransactionsInfo
                        {
                            Date = deposit.Date,
                            AccountTo = deposit.AccountId,
                            PayerType = deposit.PayerType,
                            PayerId = deposit.PayerId,
                            Amount = deposit.Amount,
                            MethodId = deposit.MethodId,
                            Description = deposit.Description
                        });
                    if (count > 0) _db.UpdateBalance(_db.BankAccounts.Find(deposit.AccountId), (double)deposit.Amount);
                    dbTransaction.Commit();
                    TempData["Toastr"] = Toastr.Updated;

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
                finally
                {
                    ViewBag.Accounts = new SelectList(_db.BankAccounts.ToList(), "Id", "AccountName", deposit.AccountId);
                    ViewBag.PayerTypes = Common.ToSelectList<PayerType>(deposit.PayerType);
                    ViewBag.PaymentMethods = new SelectList(_db.PaymentMethods.ToList(), "Id", "MethodName", deposit.MethodId);
                }
            }
        }

        // POST: Deposits/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            using (var dbTransaction = _db.Database.BeginTransaction())
            {
                try
                {
                    if (id == null)
                    {
                        TempData["Toastr"] = Toastr.BadRequest;
                        return RedirectToAction("Index");
                    }
                    var transaction = _db.TransactionsInfos.FirstOrDefault(x => x.Id==id && x.TransactionType == TransactionType.Deposit);
                    if (transaction == null)
                    {
                        TempData["Toastr"] = Toastr.HttpNotFound;
                        return RedirectToAction("Index");
                    }
                    var amount = transaction.Amount;
                    var account = _db.BankAccounts.Find(transaction.AccountTo);
                    _db.TransactionsInfos.Remove(transaction);
                    if (_db.SaveChanges() > 0) _db.UpdateBalance(account, (double) amount, BalanceMode.Decrement);
                    dbTransaction.Commit();

                    TempData["Toastr"] = Toastr.Deleted;
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    dbTransaction.Rollback();
                    TempData["Toastr"] = Toastr.DbError(ex.Message);
                    return RedirectToAction("Index");
                }
            }
        }

        [HttpPost]
        public ActionResult GetAdditionalPayerTypeFields(PayerType? payerType, int? id = null)
        {
            var model = new DepositViewModel();
            if (id != null)
            {
                var transaction = _db.TransactionsInfos.Find(id);

App.Web/Views/Deposits/Create.cshtml
@model App.Web.Models.DepositViewModel

@{
    ViewBag.Title = "Add New Deposit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h6 class="card-header bg-primary">DEPOSITS / ADD NEW</h6>
    <div class="card-block">
        <div class="row">
            @using (Html.BeginForm("Create", "Deposits", FormMethod.Post, new { @class = "form-horizontal", @id = "depositForm" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.AccountId, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                    <div class="col-sm-4">
                        @Html.DropDownListFor(model => model.AccountId, (SelectList)ViewBag.Accounts, "Select One", new { @class = "form-control select2" })
                        @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                    <div class="col-sm-4">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control pickDate" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.PayerType, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                    <div class="col-sm-4">
                        @Html.DropDownListFor(model => model.PayerType, (SelectList)ViewBag.PayerTypes, "Select One", new { @class = "form-control select2" })
                        @Html.ValidationMessageFor(model => model.PayerType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div id="PayerTypeAdditional"></div>

                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                    <div class="col-sm-4">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @type="number" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.MethodId, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                    <div class="col-sm-4">
                        @Html.DropDownListFor(model => model.MethodId, (SelectList)ViewBag.PaymentMethods, "Select One", new { @class = "form-control select2" })
                        @Html.ValidationMessageFor(model => model.MethodId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                    <div class="col-sm-4">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-12">
                    <div class="offset-sm-4 col-sm-4">
                        <button type="submit" class="btn btn-success pull-right"> <span class="fa fa-plus"></span> Add New </button>
                    </div>
                </div>
            }
            <div class="col-md-3">
                <a href="@Url.Action("Index")" class="btn btn-info"> <span class="fa fa-chevron-left"></span> Back to List</a>
            </div>

        </div>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        function ReValidate() {
            var form = $("#depositForm");
            form.removeData("validator");
            form.removeData("unobtrusiveValidation");
            $.validator.unobtrusive.parse("#depositForm");
        }

        PickDate();
        ReSelect2();

        $("#PayerType").change(function () {
            var payerType = $(this).val();
            if (payerType !== "") {
                $.post("@Url.Action("GetAdditionalPayerTypeFields", "Deposits")", { payerType: payerType }, function (html) {
                    if (html !== null) {
                        $("#PayerTypeAdditional").empty().html(html).slideDown(500);
                        ReSelect2();
                        ReValidate();
                        return;
                    }
                    $("#PayerTypeAdditional").empty().slideUp(500);
                    return;
                });
            }
            $("#PayerTypeAdditional").empty().slideUp(500);
        });

        $("#depositForm").change(function () {
            $(this).validate();
        });
    </script>
}

App.Web/Views/Deposits/Details.cshtml
@using App.Entity.Models
@using App.Web.Helper
@using App.Web.Context
@model App.Entity.Models.TransactionsInfo

@{
    ViewBag.Title = "Airline Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var db = new CrmDbContext();
}

<div class="card">
    <h6 class="card-header bg-primary">DEPOSITS / DETAILS</h6>
    <div class="card-block">
        <div class="row">
            <div class="col-md-12">
                <h5>
                    ACCOUNT NAME: @Model.BankAccountTo.AccountName.ToUpper()
                    <a href="@Url.Action("Edit", new { id = Model.Id })" class="btn btn-primary btn-sm"> <span class="fa fa-edit"></span> Edit</a>
                </h5>
                <br />
                <table class="table table-striped m-md-b-0">
                    <tr>
                        <th width="150">@Html.DisplayNameFor(m => m.Date)</th>
                        <td>@Model.Date.NullDateToString()</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.PayerType)</th>
                        <td>@Model.PayerType</td>
                    </tr>
                    @if ( Model.PayerType == PayerType.Client)
                    {
                        <tr>
                            <th>@Html.DisplayNameFor(m => m.PayerType)</th>
                            <td>@db.ClientInfos.Where(x=>x.Id == (int)Model.PayerId).Select(x=>x.FirstName+" "+x.LastName).FirstOrDefault()</td>
                        </tr>
                    }
                    @if (Model.PayerType == PayerType.Agent)
                    {
                        <tr>
                            <th>@Html.DisplayNameFor(m => m.PayerType)</th>
                            <td>@db.AgentInfos.Where(x => x.Id == (int)Model.PayerId).Select(x => x.AgentName).FirstOrDefault()</td>
                        </tr>
                    }
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.Amount)</th>
                        <td>@Model.Amount</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.MethodId)</th>
                        <td>@Model.PaymentMethod.MethodName</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.Description)</th>
                        <td>@Model.Description</td>
                    </tr>
                </table>
            </div>
        </div>
        <br />
        <div class="col-md-3">
            <a href="@Url.Action("Index")" class="btn btn-info"> <span class="fa fa-chevron-left"></span> Back to List</a>
        </div>
    </div>

</div>

App.Web/Views/Deposits/Edit.cshtml
@model App.Web.Models.DepositViewModel

@{
    ViewBag.Title = "Edit Deposit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h6 class="card-header bg-primary">DEPOSITS / EDIT</h6>
    <div class="card-block">
        <div class="row">
            @using (Html.BeginForm("Edit", "Deposits", FormMethod.Post, new { @class = "form-horizontal", @id = "depositForm" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model=>model.Id)

                <div class="form-horizontal">

                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.AccountId, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                        <div class="col-sm-4">
                            @Html.DropDownListFor(model => model.AccountId, (SelectList)ViewBag.Accounts, "Select One", new { @class = "form-control select2" })
                            @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                        <div class="col-sm-4">
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control pickDate" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.PayerType, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                        <div class="col-sm-4">
                            @Html.DropDownListFor(model => model.PayerType, (SelectList)ViewBag.PayerTypes, "Select One", new { @class = "form-control select2" })
                            @Html.ValidationMessageFor(model => model.PayerType, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div id="PayerTypeAdditional"></div>

                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                        <div class="col-sm-4">
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.MethodId, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                        <div class="col-sm-4">
                            @Html.DropDownListFor(model => model.MethodId, (SelectList)ViewBag.PaymentMethods, "Select One", new { @class = "form-control select2" })
                            @Html.ValidationMessageFor(model => model.MethodId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
                        <div class="col-sm-4">
                            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        <div class="offset-sm-4 col-sm-4">
                            <button type="submit" class="btn btn-success pull-right"> <span class="fa fa-plus"></span> Save Changes </button>
                        </div>
                    </div>

                </div>
            }
            <div class="col-md-3">
                <a href="@Url.Action("Index")" class="btn btn-info"> <span class="fa fa-chevron-left"></span> Back to List</a>
            </div>

        </div>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        PickDate();
        ReSelect2();

        function ReValidate() {
            var form = $("#depositForm");
            form.removeData("validator");
            form.removeData("unobtrusiveValidation");
            $.validator.unobtrusive.parse("#depositForm");
        }

        function GetAdditionalPayerTypeFields() {
            var payerType = $("#PayerType").val();
            if (payerType !== "") {
                var id = $("#Id").val();
                $.post("@Url.Action("GetAdditionalPayerTypeFields", "Deposits")", { id : id, payerType : payerType }, function(html) {
                    if (html !== null) {
                        $("#PayerTypeAdditional").empty().html(html).slideDown(500);
                        ReSelect2();
                        ReValidate();
                        return;
                    }
                    $("#PayerTypeAdditional").empty().slideUp(500);
                    return;
                });
            }
            $("#PayerTypeAdditional").empty().slideUp(500);
        }

        $(function() {
            GetAdditionalPayerTypeFields();

            $("#PayerType").change(function () {
                GetAdditionalPayerTypeFields();
            });
        });
    </script>
}

App.Web/Views/Deposits/Index.cshtml
@using App.Entity.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section AdditionalStyles
{
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/Content/MvcGridPagination.css" rel="stylesheet" />
    <link href="~/vendor/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
}

@using (Html.BeginForm("Delete", "Deposits", FormMethod.Post, new { @style = "display:none;", @id = "deleteForm" }))
{
    @Html.Hidden("Id")
}
<div class="card">
    <h6 class="card-header bg-primary">DIPOSITS / LIST</h6>
    <div class="card-block">
        <div class="row">
            <div class="col-md-6">
                <a href="@Url.Action("Create")" class="btn btn-info"> <span class="fa fa-plus"></span> Create New</a>
                <button class="btn btn-outline-info refreshBtn"><span class="fa fa-refresh"></span> Refresh</button>
            </div>
            <br /><br /> <br />
            <div class="col-md-12">
                @Html.Partial("~/Views/Shared/_MVCGridToolbar.cshtml", new MVCGridToolbarModel()
                {
                    MVCGridName = "depositsTable",
                    PageSize = true,
                    GlobalSearch = true
                })
                @Html.MVCGrid("depositsTable")
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/MVCGridHandler.axd/script.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/Scripts/index.js"></script>
    <script>
        @if (TempData["Toastr"] != null)
        {
            @Html.Raw(TempData["Toastr"])
        }

        $(".refreshBtn").click(function() {
            MVCGrid.reloadGrid('depositsTable');
        });
    </script>
}

App.Web/Views/Deposits/_AdditionalAgentField.cshtml
@using App.Web.Context
@model App.Web.Models.DepositViewModel

@{
    var db = new CrmDbContext();
    ViewBag.Agents = new SelectList(db.AgentInfos, "Id", "AgentName");
}

<div class="form-group col-md-12">
    @Html.LabelFor(model => model.PayerId, "Agent", htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
    <div class="col-sm-4">
        @Html.DropDownListFor(model => model.PayerId, (SelectList)ViewBag.Agents, "Select One", new { @class = "form-control select2", @required="required" })
        @Html.ValidationMessageFor(model => model.PayerId, "", new { @class = "text-danger" })
    </div>
</div>

App.Web/Views/Deposits/_AdditionalClientFileld.cshtml
@using App.Web.Context
@model App.Web.Models.DepositViewModel

@{
    var db = new CrmDbContext();
    ViewBag.Clients = new SelectList(db.ClientInfos, "Id", "FirstName");
}

<div class="form-group col-md-12">
    @Html.LabelFor(model => model.PayerId, "Client", htmlAttributes: new { @class = "control-label col-sm-4 text-md-right" })
    <div class="col-sm-4">
        @Html.DropDownListFor(model => model.PayerId, (SelectList)ViewBag.Clients, "Select One", new { @class = "form-control select2", @required = "required" })
        @Html.ValidationMessageFor(model => model.PayerId, "", new { @class = "text-danger" })
    </div>
</div>